### ISSUE TITLE
kyverno flux images: autogen-verify-cosign-signature: missing digest for ghcr.io/fluxcd/helm-controller:v0.32.2

### ISSUE THREAD

**Issue by schmidp** [fluxcd/flux2-multi-tenancy#102]
Hi,

I installed a fresh version of the kyverno helm chart 3.0.0-beta.1 and added the policy from here: https://github.com/fluxcd/flux2-multi-tenancy/blob/main/infrastructure/kyverno-policies/verify-flux-images.yaml

After a minute or so I receive the following message from via a flux alert:

```
kustomization/flux-system.flux-system
Deployment/flux-system/helm-controller dry-run failed, error: admission webhook "validate.kyverno.svc-fail" denied the request:
policy Deployment/flux-system/helm-controller for resource violation:
verify-flux-images:
 autogen-verify-cosign-signature: missing digest for [ghcr.io/fluxcd/helm-controller:v0.32.2](http://ghcr.io/fluxcd/helm-controller:v0.32.2)
revision
main@sha1:f6efb5c770c027109fe553419f5ddc97f9b9d034
```

I found that if I add `verifyDigest: false` to the images like this:

```
verifyImages:
      - image: "ghcr.io/fluxcd/helm-controller:*"
        repository: "ghcr.io/fluxcd/helm-controller"
        verifyDigest: false
        roots: |
          -----BEGIN CERTIFICATE-----
          MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
          KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
          MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
          LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
          XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
          X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
          YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
          wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
          KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
          WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
          TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
          -----END CERTIFICATE-----
```

I get another error:

```
kustomization/flux-system.flux-system
Deployment/flux-system/helm-controller dry-run failed, error: admission webhook "validate.kyverno.svc-fail" denied the request:
policy Deployment/flux-system/helm-controller for resource violation:
verify-flux-images:
 autogen-verify-cosign-signature: image is not verified
revision
main@sha1:e2d2ff8a9a43bfb23d26ae6c968ae0be217c8ac8
```

Any hints how I could further debug this? Is this maybe a kyverno 1.10 problem?

**Comment by stefanprodan** [comment]
Hey @schmidp can you please report this to the Kyverno team? Using cosign works ok, so I guess it's a Kyverno issue

```console
$ cosign verify ghcr.io/fluxcd/helm-controller:v0.32.2 --certificate-identity-regexp=github.com/fluxcd --certificate-oidc-issuer=https://token.actions.githubusercontent.com

Verification for ghcr.io/fluxcd/helm-controller:v0.32.2 --
The following checks were performed on each of these signatures:
  - The cosign claims were validated
  - Existence of the claims in the transparency log was verified offline
  - The code-signing certificate was verified using trusted certificate authority certificates
```

**Comment by stefanprodan** [comment]
@schmidp can you please try:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-flux-images
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-cosign-signature
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - imageReferences:
            - "ghcr.io/fluxcd/source-controller:*"
            - "ghcr.io/fluxcd/kustomize-controller:*"
            - "ghcr.io/fluxcd/helm-controller:*"
            - "ghcr.io/fluxcd/notification-controller:*"
            - "ghcr.io/fluxcd/image-reflector-controller:*"
            - "ghcr.io/fluxcd/image-automation-controller:*"
          attestors:
            - entries:
                - keyless:
                    subject: "https://github.com/fluxcd/*"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev
```

**Comment by schmidp** [comment]
Hello @stefanprodan thanks your support. its still the same result though:

```
kustomization/flux-system.flux-system
Deployment/flux-system/helm-controller dry-run failed, error: admission webhook "validate.kyverno.svc-fail" denied the request:
policy Deployment/flux-system/helm-controller for resource violation:
verify-flux-images:
 autogen-verify-cosign-signature: missing digest for [ghcr.io/fluxcd/helm-controller:v0.32.2](http://ghcr.io/fluxcd/helm-controller:v0.32.2)
revision
main@sha1:8c86fc378912c3ace38b1e232ad81c6a6560ac8f
summary
```

Probably a kyverno 1.10 problem then...

**Comment by chipzoller** [comment]
The policy currently referenced in this repo uses deprecated language and is in need of an update.

I have verified that this policy works across all current Flux images as named in the original policy. I have also verified this policy works for those images across Kyverno versions 1.7-1.10. I recommend updating the policy in this repo but have not done so through a PR in case further discussion is first needed.

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-flux-images
spec:
  validationFailureAction: enforce
  webhookTimeoutSeconds: 30
  background: false
  failurePolicy: Fail
  rules:
    - name: verify-cosign-signature
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/fluxcd/helm-controller*"
        - "ghcr.io/fluxcd/kustomize-controller*"
        - "ghcr.io/fluxcd/notification-controller*"
        - "ghcr.io/fluxcd/source-controller*"
        - "ghcr.io/fluxcd/image-automation-controller*"
        - "ghcr.io/fluxcd/image-reflector-controller*"
        mutateDigest: true
        verifyDigest: true
        required: true
        attestors:
        - entries:
          - certificates:
              certChain: |-
                -----BEGIN CERTIFICATE-----
                MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
                KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
                MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
                LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
                XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
                X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
                YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
                wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
                KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
                WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
                TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
                -----END CERTIFICATE-----
```
