### ISSUE TITLE
kyverno: missing digest for ghcr.io/fluxcd/helm-controller:v0.34.1

### ISSUE THREAD

**Issue by Pro** [fluxcd/flux2-multi-tenancy#107]
I was following the docs on multi-tenancy-setup using kind.
(Am not that experienced yet with Flux, be patient ;))

Running flux with the exact same version as this repo, I get the following error:

```
2023-06-09T12:10:16.906Z error Kustomization/flux-system.flux-system - Reconciliation failed after 11.419728509s, next try in 10m0s Deployment/flux-system/helm-controller dry-run failed: admission webhook "validate.kyverno.svc-fail" denied the request: 

resource Deployment/flux-system/helm-controller was blocked due to the following policies 

verify-flux-images:
  autogen-verify-cosign-signature: missing digest for ghcr.io/fluxcd/helm-controller:v0.34.1
```

Is this something I can fix, or is there some key missing on the sigstore server?

**Comment by stefanprodan** [comment]
It could be that https://github.com/fluxcd/flux2-multi-tenancy/pull/106 broke the policies or this is a Kyverno bug. Can you please post here what Kyverno version are you using?

PS. Maybe we should use the [sigstore/policy-controller](https://github.com/sigstore/policy-controller) which may be less buggy when it comes to verifying signatures. Right now, our e2e tests are not able to detect these types of issues with Kyverno, as the validation happens in the background. cc @hiddeco @makkes

**Comment by stefanprodan** [comment]
@Pro are you using the policy from the main branch? The error message you posted is for Deployments but we’ve set the policy for pods https://github.com/fluxcd/flux2-multi-tenancy/blob/main/infrastructure/kyverno-policies/verify-flux-images.yaml#L16

**Comment by Pro** [comment]
Ok, sorry, have to re-open. This seems to be randomly happening.

I.e., using the following setup:
https://github.com/Pro/flux2-multi-tenancy/tree/monitoring

Reproduction:

create a file `kind-config.yaml`:

```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gl-staging
networking:
  apiServerPort: 6443
  # the default CNI will not be installed
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16 # set to Calico's default subnet
nodes:
- role: control-plane
  image: kindest/node:v1.27.2@sha256:ff631c3718962dc5a5e8adf1f48803c2675feebcd4eef674dd5a943576cf1d33
- role: worker
  image: kindest/node:v1.27.2@sha256:ff631c3718962dc5a5e8adf1f48803c2675feebcd4eef674dd5a943576cf1d33
```

and then use the following commands to start kind and bootstrap (set the git credentials first)

```shell
kind delete cluster --name gl-staging

kind create cluster --config kind-config.yaml
kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/calico.yaml
kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true

flux bootstrap git --silent --url=https://github.com/Pro/flux2-multi-tenancy.git --private-key-file=$HOME/.ssh/id_ed25519 --path=clusters/staging --branch=monitoring
```

You will then see the following reconciliation error on the flux-system:

> error Kustomization/flux-system.flux-system - Reconciliation failed after 679.628428ms, next try in 10m0s Deployment/flux-system/helm-controller dry-run failed: admission webhook "validate.kyverno.svc-fail" denied the request: 
> 
> resource Deployment/flux-system/helm-controller was blocked due to the following policies 
> 
> verify-flux-images:
>   autogen-verify-cosign-signature: missing digest for ghcr.io/fluxcd/helm-controller:v0.34.1
> 

kyverno version: 1.10.0

Using the patch from #108 also does not work. Then `kyverno-policies` will fail with:

> ClusterPolicy/verify-flux-images dry-run failed: admission webhook "validate-policy.kyverno.svc" denied the request: spec.rules[0].verifyImages[0].mutateDigest: Invalid value: true: mutateDigest must be set to false for ‘Audit’ failure action
