### ISSUE TITLE
How do I allow a tenant's service account to create clusterresources?

### ISSUE THREAD

**Issue by AHulshoff** [fluxcd/flux2-multi-tenancy#131]
I am trying to setup a multi-tenant environment, where I can separate responsibilities in teams. However, when I am trying to install some helm charts, I get the following errors:

> 2024-09-12T16:44:39.048Z error HelmRelease/nfs-subdir-external-provisioner.platform - Reconciler error Unable to continue with install: could not get information about the resource StorageClass "nfs-client" in namespace "": storageclasses.storage.k8s.io "nfs-client" is forbidden: User "system:serviceaccount:platform:platform-team" cannot get resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
2024-09-12T16:44:42.386Z error HelmRelease/cert-manager.platform - Reconciler error Unable to continue with install: could not get information about the resource CustomResourceDefinition "certificaterequests.cert-manager.io" in namespace "": customresourcedefinitions.apiextensions.k8s.io "certificaterequests.cert-manager.io" is forbidden: User "system:serviceaccount:platform:platform-team" cannot get resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
2024-09-12T16:45:03.108Z error HelmRelease/metrics-server.platform - Reconciler error Unable to continue with install: could not get information about the resource ClusterRole "system:metrics-server-aggregated-reader" in namespace "": clusterroles.rbac.authorization.k8s.io "system:metrics-server-aggregated-reader" is forbidden: User "system:serviceaccount:platform:platform-team" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
2024-09-12T16:45:03.144Z error HelmRelease/purelb.platform - Reconciler error failed to apply CustomResourceDefinitions: failed to create CustomResourceDefinition lbnodeagents.purelb.io: 1 error occurred:
        * customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:platform:platform-team" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

As you can see, I have issues retrieving storageclasses, customresourcedefinitions and clusterroles and creating customresourcedefinitions.

I have created the following file:
```yaml
# rbac.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform-team
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-permissions
  namespace: platform
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["CustomResourceDefinitions", "ClusterRoles"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform-team-reconciler
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:platform:reconciler
- kind: ServiceAccount
  name: platform-team
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform-team-crds
  namespace: platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: platform-permissions
subjects:
  - kind: ServiceAccount
    name: platform-team
    namespace: platform
```

But this doesn't seem to work... Can anyone point me in the right direction?

**Comment by stefanprodan** [comment]
IMO the `platform-team` should have cluster admin, if it needs to create cluster roles, then a custom RBAC is useless. So I would just do:

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform-team
  namespace: platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: platform-team
  name: platform-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: platform-team
    namespace: platform
```

Make sure that the Flux Kustomizations and HelmReleases in the `platform` namespace have `serviceAccountName: platform-team`.
