### ISSUE TITLE
Flux tenants using helm

### ISSUE THREAD

**Issue by rverma-nsl** [fluxcd/flux2-multi-tenancy#32]
In continuation of https://github.com/fluxcd/flux2-multi-tenancy/issues/27, 

if we have defined clusters/tenants.yaml as helmreases with chart source as ./tenants/base/dev-team, we could have saved generation of 5 files (provided helm controller start generating Chart.yaml, like kustomization controller).

Further the tenants are actually not a child entity of clusters, both clusters and tenants could have many to many mapping.
Couldn't the whole design  be from the prospective of tenants then clusters? i.e. In place of tenants having refs to clusters, we can easily have clusters having refs to tenants.

This can also simplify the no. of hops one need to understand setup.

A simple example is 

```
# cluster/production/tenants.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  namespace: flux-system
  name: tenants
spec:
  chart:
    spec:
      chart: ./tenants
      sourceRef:
        name: flux-system
        kind: GitRepository
  interval: 1m
  values:
    dev-team: true
    qa-team: false
```

and 
```
tenants/templates/dev-team.yaml
```
{{-if .Values.dev-team }}
content of rbac.yaml
content of sync.yaml
{{-end }}
```

If we can modify flux to support the tenants more natively, may be a crd etc. 
So that the above example tenants rbac and sync also reduces drastically

e.g 

```
# cluster/production/tenants.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: TenantsAllocation
metadata:
  name: cluster-name
  namespace: flux-system
spec:
  interval: 1m
  tenants
   - name: dev-team
     serviceAccountName: dev-team
      namespaces: 
            - dev-a
            - dev-b
      sourceRef:
        kind: GitRepository
        name: flux-system
      path: ./tenants/services/ap-south-1
   - name: qa-team
     serviceAccountName: dev-team
      namespaces: 
            - dev-a
            - qa-a
      sourceRef:
        kind: GitRepository
        name: flux-system
      path: ./tenants/services/ap-south-1
```
This setup should drastically reduce the no of vanilla files.
