### ISSUE TITLE
how to set up multiple tenants in one cluster

### ISSUE THREAD

**Issue by brant4test** [fluxcd/flux2-multi-tenancy#41]
Hi, Team,

In flux2-multi-tenancy repo, there's only one tenant called "dev-team", what if I need to add "tenant2" even "tenant3"... in the future?
https://github.com/fluxcd/flux2-multi-tenancy

Say for staging cluster specifically, currently you're assuming only one tenant in staging cluster below, right?
Under directory "./clusters/staging"

https://github.com/fluxcd/flux2-multi-tenancy/blob/d5f3a08f9ed932466608d04fde7dfed7b0f53772/clusters/staging/tenants.yaml#L13

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  path: ./tenants/staging
```

Could I add tenant2 following these steps? or do you have recommended pattern for multi-tenancy in one cluster? Thanks!

1. modify dev-team Kustomization to:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant-dev-team
  namespace: flux-system
spec:
  path: ./tenants/staging/dev-team
```

2. add tenant2 Kustomization:

```
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenant2
  namespace: flux-system
spec:
  path: ./tenants/staging/tenant2
```

so directory "./clusters" would contain the following directories and files:

```
├───production
└───staging
    ├───flux-system
    ├───infrastructure.yaml
    ├───tenant-dev-team.yaml
    └───tenant2.yaml
```

3. Under directory "./tenants/staging/" make the changes like these:

```
├───base
│   ├───dev-team
│   │   │───sync.yaml
│   │   │───rbac.yaml
│   │   └───kustomization.yaml
│   └───tenant2
│       │───sync.yaml
│       │───rbac.yaml
│       └───kustomization.yaml
├───production
└───staging
    ├───dev-team
    │   │───dev-team-patch.yaml
    │   └───kustomization.yaml
    └───tenant2
        │───tenant2-patch.yaml
        └───kustomization.yaml
```

So that eventually tenant dev-team and tenant2 could point to respective repository.
